# Mailer Configuration.
mailer:
  # SMTP mailer configuration.
  smtp:
    # Enable/Disable smtp mailer.
    enable: true
    # SMTP server host. e.x localhost, smtp.gmail.com
    host: {{ get_env(name="MAILER_HOST", default="smtp.example.com") }}
    # SMTP server port
    port: {{ get_env(name="MAILER_PORT", default=0) }}
    # Use secure connection (SSL/TLS).
    secure: true
    auth:
      user: {{ get_env(name="MAILER_USERNAME", default="username") }}
      password: {{ get_env(name="MAILER_PASSWORD", default="password") }}
    # Override the SMTP hello name (default is the machine's hostname)
    # hello_name:
